### ISSUE TITLE
Mock model constructor

### ISSUE THREAD

**Issue by FiddlinBill** [underscopeio/sinon-mongoose#10]
Is it possible to mock the model constructor with sinon-mongoose? This package works fine for mocking named model methods but throws an error if the method name is falsy.

```javascript
MyModel
    .expects('')
    .resolves({});
```

Thanks!

**Comment by gaguirre** [comment]
Hi @FiddlinBill, why do you need to mock the contructor?
Could you post the piece of code you want to test?

**Comment by FiddlinBill** [comment]
I wanted to return some fake data from the constructor, including a stub for the save() method. I am using Sinon by the way. I am trying to make the save() method throw an error to test my error handling.

// code I want to test
...
     var newThread = {
         lots: 'of stuff'
    }

    // create the new thread
    newThread = new ThreadModel(newThread);
    return newThread.save();
...

Thanks for the quick reply!

**Comment by gaguirre** [comment]
Ok, for this case i suggest you to use
```javascript
ThreadModel.create(newThread)
// instead of 
newThread = new ThreadModel(newThread)
return newThread.save()
```

The method `create` is a shortcut for the constructor and the save method.

**Comment by FiddlinBill** [comment]
Well that would make it easier to stub! Thank you!

**Comment by gaguirre** [comment]
And it has the benefit that can be mocked as any other method. This way you can test your code like
```javascript
sinon.mock(ThreadModel).expects('create').withArgs({ lots: 'of stuff' })
```
