### ISSUE TITLE
Make sure that methods are being called in the right order

### ISSUE THREAD

**Issue by nschurmann** [underscopeio/sinon-mongoose#11]
I have a handler written this way:

```javascript
exports.index = Todos => (req, res) => {
  Todos
    .find(req.params)
    .limit(10)
    .exec()
    .then(x => {
      process.end()
      res.send(x)})
}
```

And i want to test that the methods are called exactly in that order. I'm writing the test like this:

```javascript
it('should fail', () => {
      var TodoMock = sinon.mock(Todo)
      TodoMock
        .expects('find').withArgs({id: 'some id'})
        .chain('where').withArgs({as:'random'})
        .chain('exec')
        .resolves('lkjdsajlkdsajlkas')
      handler.index(Todo)({params: {id : 'some id'}}, res)
      TodoMock.verify()
    })
```

But it passes... if i change the expectation object, instead of `{id: 'some id'}` to anything else it fails. How can i test the order that is being called and the args?

**Comment by gaguirre** [comment]
Hi @nschurmann, sorry for the delay! Could you post a real case? 

In the example you provide you're expecting a call to `where` in the test (`.chain('where').withArgs({as:'random'})`) but not calling it in your code.

**Comment by gaguirre** [comment]
Also you're calling `process.end()` before `res.send(x)`.
Could you check that's not the problem?

**Comment by nschurmann** [comment]
Sorry, can't check it right now, we switched to sinon as promised and all methods stubed are returning this. Is not the best but it's doing well.

**Comment by gaguirre** [comment]
No problem! I'll be answer faster next time ;)
BTW, I don't fully understand why you want to test the calls order (besides the first and last call, i.e. `find` and `exec`, the other methods order should produce the same result)

**Comment by nschurmann** [comment]
@gaguirre i think you are right, i should not test the order of the others, except for find and exec.

**Comment by gaguirre** [comment]
👍 great!
And again, sorry for the late answer
