### ISSUE TITLE
Support for sinon sandboxes

### ISSUE THREAD

**Issue by jniemin** [underscopeio/sinon-mongoose#15]
Seems that if creating mock through sandbox, the chainable is not assigned. 

```
var sandbox = sinon.sandbox.create();
var Mock = sandbox.mock(MyMongooseObject);
Mock.expect('findOne').chain('populate');
```

This example fails with error:
`TypeError: Mock.expects(...).chain is not a function`

Using sandbox is more convenient as you can easily just create as many mocks you like and then do `sandbox.restore` which will restore all mocks rather than restoring each mock separately.

**Comment by gaguirre** [comment]
@jniemin it should work... actually I always use sandbox.
Could you post a complete example?

**Comment by jniemin** [comment]
Here is complete the example @gaguirre. I'm using Mocha 3.2.0, sinon 2.1.0, and sinon-mongoose 1.3.0 

roles.js
```
"use strict";

const mongoose = require('mongoose');
const Schema   = mongoose.Schema;

const ROLES_SCHEMA = new Schema({
  name:{
    type:String
  }
},{
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at'
  }
});

const Role = mongoose.model('Role', ROLES_SCHEMA);

module.exports = Role;
```

roles.spec.js
```
"use strict";

const Role = require('./roles');
const sinon = require('sinon');
require('sinon-mongoose');
const sinonSandbox = sinon.sandbox;

describe("sinon-mongoose sandbox", function(){
  afterEach(function() {
    sinonSandbox.restore();
  });

  it("Chaining should work when using sinon sandbox", function(){
    // throws error "TypeError: RoleMock.expects(...).chain is not a function"
    const RoleMock = sinonSandbox.mock(Role);
    RoleMock.expects('findOne').chain('populate').resolves({});
  });

  it("Chaining works when using mock not created by sandbox", function(){
    const RoleMock = sinon.mock(Role);
    RoleMock.expects('findOne').chain('populate').resolves({});
    RoleMock.restore();
  })

});

```

**Comment by gaguirre** [comment]
You're missing the sandbox creation. It should be
```
const sinonSandbox = sinon.sandbox.create()
```

Tell me if it works!

**Comment by jniemin** [comment]
Ah, copy paste error, when I removed some of the business names etc. So sandbox.create() is in the actual test code. So still no luck

**Comment by gaguirre** [comment]
Weird. There is a test using sandbox (https://github.com/underscopeio/sinon-mongoose/blob/master/test/index.js#L116).
Check it out, it may be helpful.

**Comment by jniemin** [comment]
Seems that if I ran sinon-mongoose tests from master there it works. I wonder could it be sinon-mongoose using older versions of sinon (1.17.7) and mocha (2.5.3)? I'm running on my own project sinon 2.1.0 and mocha 3.2.0.

**Comment by gaguirre** [comment]
Maybe... Could you try upgrading sinon for the tests and see if it fails.
Then probably it needs a fix for newer sinon versions.
Thanks @jniemin!

**Comment by jniemin** [comment]
It definitely was then new version of Sinon that made the tests break. I created PR to add support for Sinon 2.

**Comment by jniemin** [comment]
Actual implementation was not totally proper. There is now new PR to fix that
