### ISSUE TITLE
How to verify that some functions are not called

### ISSUE THREAD

**Issue by jniemin** [underscopeio/sinon-mongoose#20]
I was wondering what is the best way to test that some of the functions are not called. If I chain some expectation, then it resolves it incorrectly.  In this case it exec doesn't resolve to "RESULT" but undefined.

```
it('#fail', function(done) {
      var bookMock = sinon.mock(new Book({ title: 'Rayuela' }));

      bookMock.expects('update')
        .chain('sort').never()
        .chain('exec').resolves("RESULT");

      bookMock.object.update('SOME_ARGUMENTS').exec().then(function(result) {
        try{
          assert.equal(result, 'RESULT');
          bookMock.verify();
          bookMock.restore();         
          done();
        }catch(err){
          done(err)
        }
      });
    });
```

Also if I try to verify that was sort was called but it was never called, bockMock.verify() passes nicely.

```
it('#fail', function(done) {
      var bookMock = sinon.mock(new Book({ title: 'Rayuela' }));

      bookMock.expects('update')
        .chain('sort').withArgs("sort parameters")
        .chain('exec').resolves("RESULT");

      bookMock.object.update('SOME_ARGUMENTS').exec().then(function(result) {
        try{ 
          bookMock.verify();
          bookMock.restore();
          assert.fail(false, true, "should fail to mock.verify()");
          done();
        }catch(err){
          done(err)
        }
      });
    });
```

Seems that bockMock.verify() only calls verify for first expection which is call to 'update' and rest of the chained mocks are not verified

**Comment by gaguirre** [comment]
Oh, it seems like a bug. Maybe it's something related to the `sinon` upgrade.
If you find something could be useful just post it here ;)

Thanks for reporting this! I'll take a look at it later.

**Comment by jniemin** [comment]
@gaguirre Would you have time to check the new PR. I would need a new version released, so that I can reference to it in my code :)

**Comment by jniemin** [comment]
@gaguirre Any change to check the latest changes to PR and release new version
