### ISSUE TITLE
How to mock virtuals

### ISSUE THREAD

**Issue by yereby** [underscopeio/sinon-mongoose#26]
Hi,
Is it possible to mock the virtuals methods like this :
```js
userSchema.virtual('firstname').get(function firstname () {
  return this.name.split(' ')[0]
})
```

I tried this but the coverage says i don't pass threw it :
```js
const userNewMock = sinon.mock(new User(fakeUser))
userNewMock
  .expects('get').withArgs('firstname')
  .resolves(fakeUser.firstname)
```

Thanks.

**Comment by gaguirre** [comment]
I guess you can test the virtuals without mocking anything. Considering you've defined this method
```
userSchema.virtual('firstname').get(function firstname () {
  return this.name.split(' ')[0]
})
```
You could instance a new User and then just assert the virtual method is working
```
const user = new User({ name: 'MOCK_NAME' })
//  assert that user.firstname == 'MOCK_NAME'
```

**Comment by yereby** [comment]
Hoho well you are right, i was stuck in sinon and didn't see it.  
Thanks a lot.
