### ISSUE TITLE
TypeError: Attempted to wrap undefined property aggregate as function

### ISSUE THREAD

**Issue by arpitkulria** [underscopeio/sinon-mongoose#33]
I have a use case like this

`Question.aggregate([{ $match: { topic: quizId } }, { $sample: { size: count * 2 } }]).then(questionsFromDb => (_.uniqBy(questionsFromDb, '_id').slice(0, count)));`

but when I try 

`QuestionMock.expects('aggregate').withArgs([{ $match: { topic: 1 } }, { $sample: { size: 2 } }])
      .yield(null, { data: 'data' });
`
It is giving error

> TypeError: Attempted to wrap undefined property aggregate as function

Any idea what's going on?
Thanks in advance.

**Comment by gaguirre** [comment]
Hi @arpitkulria, what's `QuestionMock` in this case? Could you post the complete example isolating the problem? 
Thanks!

**Comment by arpitkulria** [comment]
Actually, I was trying to mock the `aggregate ` fucntion, but then I choose different approch

something like this

`import sinon from 'sinon'`
` const sandbox = sinon.sandbox;`
 `sandbox.stub(mongoose.Model, 'aggregate').resolves(someJsonData);`

But thanks for the reply :)
