### ISSUE TITLE
sinon 5 release - peer dependency warn

### ISSUE THREAD

**Issue by YasharF** [underscopeio/sinon-mongoose#34]
With sinon 5 release, if a user installs the latest version of sinon, they may get the following error when running `npm install`:

`npm WARN sinon-mongoose@2.1.1 requires a peer of sinon@2.1 - 4 but none is installed. You must install peer dependencies yourself.`

**Comment by YasharF** [comment]
sure
It looks like that `npm audit` is tagging a bunch of packages with issues, so I'll bump a few more packages while updating package.json:

```
found 26 vulnerabilities (5 low, 11 moderate, 10 high) in 3047 scanned packages
  run `npm audit fix` to fix 4 of them.
  16 vulnerabilities require semver-major dependency updates.
  6 vulnerabilities require manual review. See the full report for details.
```

**Comment by YasharF** [comment]
The scope of adding sinon 5 and 6 seem to be a breaking change and I think I need help with someone else taking over the change.  I was able to help upgrade a bunch of other packages while looking at the sinon upgrade though.

**Comment by gaguirre** [comment]
Indeed, it looks there's a breaking change. I'll take a look later today and see if I can solve that issue.
Thanks for all the info! 😉
