### ISSUE TITLE
Doesn't support .stub()

### ISSUE THREAD

**Issue by antony** [underscopeio/sinon-mongoose#5]
I'm using a few things in my project:

* sandboxing - which seems to work fine
* stub - which doesn't appear to be supported
* this syntax: sandbox.stub(Lenders, 'all') - which also appears to be unsupported

It'd be nice if this module supported the full sinon syntax, as it is otherwise really useful.

**Comment by gaguirre** [comment]
Hi @antony, could you post an example of what you would like to do exactly?
This module extends sinon, so you can use all the methods it already has.

**Comment by gaguirre** [comment]
@antony I assume you already figured out you can use `sinon.stub` as always. If not please reopen!

**Comment by qqilihq** [comment]
I am having the same issue and I am a little confused by the answer. Is `stub` supposed to work or not? Here's an example of what I'm trying to do:

     this.stub(Model).chain('select').chain('exec').resolves(new Model({ foo: 'bar' }))

Gives me: `TypeError: this.stub(...).chain is not a function`

**Comment by qqilihq** [comment]
@gaguirre Great, thanks a bunch!
