### ISSUE TITLE
How to chain query helpers

### ISSUE THREAD

**Issue by ms007** [underscopeio/sinon-mongoose#6]
I use query helpers 

    animalSchema.query.byName = function(name) {
        return this.find({ name: new RegExp(name, 'i') });
    };

    var Animal = mongoose.model('Animal', animalSchema);
    Animal.find().byName('fido').exec(function(err, animals) {
        console.log(animals);
    });

How can i mock the byName call?

**Comment by gaguirre** [comment]
Hi @ms007, I think it's not a good practice to append methods to the query. Instead you could (and probably should) use [statics](http://mongoosejs.com/docs/guide.html#statics).

Your code will look like
```
animalSchema.statics.findByName = function(name) {
    return this.find({ name: new RegExp(name, 'i') });
};

var Animal = mongoose.model('Animal', animalSchema);
Animal.findByName('fido').exec(function(err, animals) {
    console.log(animals);
});
```

Then you can test it doing the following
```
sinon.mock(Animal)
  .expects('findByName')
  .withArgs('fido')
  .chain('exec')
  .resolves('SOME_VALUE');
```

If i'm not clear enough just tell me!

**Comment by ms007** [comment]
Hello @gaguirre , thank you for teaching me some mongoose best practice. I'm getting more and more familiar with it.

**Comment by gaguirre** [comment]
You are welcome! Hope this library helps you too.
