### ISSUE TITLE
Does not work with models with schema?

### ISSUE THREAD

**Issue by jishi** [underscopeio/sinon-mongoose#7]
I can't seem to get this to work with our model that are based on Schemas, i get "Cannot read property 'schema' of undefined"

I'm doing something like this:

```
const SomeModel = mongoose.model(Trip, schema);

const mockModel = sinon.mock(SomeModel);

mockModel.expects('find')
  .chain('limit', 20)
  .yields(null);

const obj = SomeModel.find().limit().exec(); //simplified, but this fails
```

This breaks when invoking the code path calls exec. Is this something to do with the mocking?

**Comment by gaguirre** [comment]
Hi @jishi, the right way to mock that call (using `sinon-mongoose`) would be
```
mockModel.expects('find')
  .chain('limit', 20)
  .chain('exec')
  .resolves(null);
```
See the docs for more info and tell me if this solves your issue!

**Comment by jishi** [comment]
But isn't that what I did, except I'm not using promises?

**Comment by gaguirre** [comment]
Oh sorry, I didn't see you were using callbacks. Then you should mock it like [this doc section](https://github.com/underscopeio/sinon-mongoose#with-callbacks-no-promises) explains
```
sinon.mock(MongooseModel)
  .expects('find')
  .chain('limit').withArgs(20)
  .chain('exec') // I guess this line was missing
  .yields(null);
```
Tell me if that make it work!

**Comment by jishi** [comment]
Still get the same error, must be something with the way I initialize my model. I get another issue when trying to use it for stubbing the save() method of a model instance. The examples I find says to mock in the instance, but that is done outside of the test code so I guess I'm fucked there as well?

I'm getting the feeling that mongoose is a pain to test...

**Comment by gaguirre** [comment]
Could you post the complete example?
As advice, start with a simple test case, make it work and then incrementally add more complex cases.

**Comment by Merott** [comment]
I think the issue with stubbing the `save` method could be that there is no setter for it, making it read-only: See this: [model.js](https://github.com/Automattic/mongoose/blob/46764ef6668e0e3c47fab674453c554e01ed6376/lib/model.js#L3291)

The workaround I found was to redefine the `save` property on the model's prototype using `Object.defineProperty`:

```
Object.defineProperty(MyModel.prototype, 'save', {
  value: MyModel.prototype.save,
  configurable: true,
});

```

Now it's possible to stub the `save` method:

```
sinon.stub(MyModel.prototype, 'save');
```

**Comment by gaguirre** [comment]
@Merott I think you should use `mock` instead of `stub` if possible.

**Comment by Merott** [comment]
For my use case I needed to provide a behaviour for the `save` method.

Even with a mock though, the test still fails unless the `save` method is explicitly rewritten with `Object.defineProperty`.

```js
// FAILS:
const mock = sinon.mock(MyModel.prototype);
mock.expects('save').exactly(1);
new MyModel().save();
mock.verify();
```

```js
// PASSES:
Object.defineProperty(MyModel.prototype, 'save', {
  value: MyModel.prototype.save,
  configurable: true,
});

const mock = sinon.mock(MyModel.prototype);
mock.expects('save').exactly(1);
new MyModel().save();
mock.verify();
```

**Comment by gaguirre** [comment]
I think it's because you should be mocking the Model instance instead of the Model prototype like this
```
const myModelInstance = new MyModel();
sinon.mock(myModelInstance).expects('save').exactly(1);

myModelInstance.save();
mock.verify();
``` 

Please let me know if this works or it doesn't.

**Comment by Merott** [comment]
I don't have access to the model from inside the test code, like @jishi mentioned earlier. 

I guess I was trying to avoid posting the entire code, thinking it would be unnecessary details. Perhaps not so unnecessary after all. Here is a more complete example, still simplified:

**`user.controller.js`:**

```js
const User = require('./user.model');

module.exports = {
  createUser(req, res) {
    const user = new User({   // see NOTE
      name: req.swagger.params.body.value.name,
    });

    user.save((err) => {
      if (!err) {
        res.status(200);
      }
    });
  },
};
```

**`user.model.js`:**

```js
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  name: String,
});

module.exports = mongoose.model('User', userSchema);
```

**`user.spec.js`:**

```js
const expect = require('chai').expect;
const sinon = require('sinon');

const userController = require('./user');
const User = require('./user.model');

describe('successful user creation', () => {
  let mockRequest;
  let mockResponse;

  beforeEach(() => {
    Object.defineProperty(User.prototype, 'save', {
      value: User.prototype.save,
      configurable: true,
    });

    mockRequest = {
      swagger: {
        params: {
          body: {
            value: {
              competitionName: 'foo',
              email: 'bar@example.com',
            },
          },
        },
      },
    };

    mockResponse = {
      resultStatus: undefined,

      status(s) {
        this.resultStatus = s;
        return this;
      },
    };

    sinon.stub(User.prototype, 'save', callback => callback());
  });

  afterEach(() => {
    User.prototype.save.restore();
  });

  it('should respond with a 200', () => {
    userController.storeUser(mockRequest, mockResponse);
    expect(mockResponse.resultStatus).to.eq(200);
  });
});
```

*NOTE*: One might argue it's better not to `new` up an instance of the `User` model inside of the controller, and instead put that logic in a factory method that can be stubbed. I personally have mixed feelings about that argument when it comes to Mongoose models though.

**Comment by gaguirre** [comment]
For this case you could use `create` on your **`user.controller.js`**
```
const User = require('./user.model');

module.exports = {
  createUser(req, res) {
    User.create({
      name: req.swagger.params.body.value.name,
    }, (err) => {
      if (!err) {
        res.status(200);
      }
    });
  },
};
```

And then test it mocking the `create` method

```
const expect = require('chai').expect;
const sinon = require('sinon');

const userController = require('./user.controller');
const User = require('./user.model');

describe('successful user creation', () => {
  let mockRequest;
  let mockResponse;

  beforeEach(() => {
    mockRequest = {
      swagger: {
        params: {
          body: {
            value: {
              competitionName: 'foo',
              email: 'bar@example.com',
            },
          },
        },
      },
    };

    mockResponse = {
      resultStatus: undefined,

      status(s) {
        this.resultStatus = s;
        return this;
      },
    };
  });

  it('should respond with a 200', () => {
    sinon.mock(User)
      .expects('create')
      .withArgs({ email: 'bar@example.com' })
      .yields(null);

    userController.createUser(mockRequest, mockResponse);
    expect(mockResponse.resultStatus).to.eq(200);
  });
});
```
